#!/usr/bin/env bash
# Build the MCPB bundle (retyc-<version>.mcpb) from a populated goreleaser dist/.
#
# The bundle is a plain ZIP with manifest.json at the root (MCPB spec). It ships
# three binaries selected at install time via manifest platform_overrides:
#   server/retyc-darwin       macOS universal (arm64 + amd64)
#   server/retyc-linux        Linux amd64
#   server/retyc-windows.exe  Windows amd64
#
# The manifest is generated by the freshly built binary itself (retyc mcp manifest),
# so its version and tool list can never drift from the code.
#
# Usage:
#   scripts/build-mcpb.sh [--expect-version X.Y.Z]
#
# Requirements: jq, zip, goreleaser dist/ (run `goreleaser release --snapshot --clean`
# or the release CI first). No Node.js needed.
set -euo pipefail

EXPECT_VERSION=""
while [ $# -gt 0 ]; do
  case "$1" in
    --expect-version) EXPECT_VERSION="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST="${ROOT}/dist"
ARTIFACTS="${DIST}/artifacts.json"
STAGE="${DIST}/mcpb"

for tool in jq zip; do
  command -v "$tool" >/dev/null || { echo "Error: '$tool' is required" >&2; exit 1; }
done
[ -f "${ARTIFACTS}" ] || { echo "Error: ${ARTIFACTS} not found. Run goreleaser first (make mcpb does it)." >&2; exit 1; }

# Locate a built binary in goreleaser's artifacts.json by goos/goarch
# (the macOS universal binary is goarch "all").
find_binary() {
  local goos="$1" goarch="$2"
  local rel
  rel=$(jq -r --arg os "$goos" --arg arch "$goarch" \
    'first(.[] | select(.type == "Binary" and .goos == $os and .goarch == $arch)) | .path // empty' \
    "${ARTIFACTS}")
  [ -n "$rel" ] || { echo "Error: no Binary artifact for ${goos}/${goarch} in artifacts.json" >&2; exit 1; }
  # goreleaser paths are relative to the working directory it ran in (repo root).
  echo "${ROOT}/${rel#"${ROOT}/"}"
}

DARWIN_BIN=$(find_binary darwin all)
LINUX_BIN=$(find_binary linux amd64)
WINDOWS_BIN=$(find_binary windows amd64)

# Pick the binary runnable on this host to generate the manifest.
case "$(uname -s)" in
  Linux)  MANIFEST_BIN="${LINUX_BIN}" ;;
  Darwin) MANIFEST_BIN="${DARWIN_BIN}" ;;
  *) echo "Error: unsupported host OS for manifest generation: $(uname -s)" >&2; exit 1 ;;
esac

rm -rf "${STAGE}"
mkdir -p "${STAGE}/server"

cp "${DARWIN_BIN}"  "${STAGE}/server/retyc-darwin"
cp "${LINUX_BIN}"   "${STAGE}/server/retyc-linux"
cp "${WINDOWS_BIN}" "${STAGE}/server/retyc-windows.exe"
chmod 755 "${STAGE}/server/retyc-darwin" "${STAGE}/server/retyc-linux"
cp "${ROOT}/mcpb/icon.png" "${STAGE}/icon.png"

"${MANIFEST_BIN}" mcp manifest > "${STAGE}/manifest.json"

# The binary names are duplicated between this script and the embedded base
# manifest: assert every command path in the manifest exists in the stage,
# otherwise the bundle would validate but fail at launch in Claude Desktop.
jq -r '.server.mcp_config | (.command, (.platform_overrides[]?.command // empty))' "${STAGE}/manifest.json" \
  | sed 's|^\${__dirname}/||' \
  | while read -r cmd_path; do
      [ -f "${STAGE}/${cmd_path}" ] || { echo "Error: manifest command '${cmd_path}' not found in stage" >&2; exit 1; }
    done

VERSION=$(jq -r .version "${STAGE}/manifest.json")
[ -n "${VERSION}" ] && [ "${VERSION}" != "null" ] || { echo "Error: no version in generated manifest" >&2; exit 1; }

if [ -n "${EXPECT_VERSION}" ] && [ "${VERSION}" != "${EXPECT_VERSION}" ]; then
  echo "Error: manifest version '${VERSION}' != expected '${EXPECT_VERSION}' (tag mismatch)" >&2
  exit 1
fi

OUT="${DIST}/retyc-${VERSION}.mcpb"
rm -f "${OUT}"
(cd "${STAGE}" && zip -q -r -X "${OUT}" manifest.json icon.png server)

echo "OK  ${OUT#"${ROOT}"/} ($(du -h "${OUT}" | cut -f1), $(jq '.tools | length' "${STAGE}/manifest.json") tools, version ${VERSION})"
